### ISSUE TITLE
Packaging build error

### ISSUE THREAD

**Issue by lumpn** [sinbad/StevesUEHelpers#10]
# What happened
There's a compiler error when packaging a standalone build.
```
StevesUEHelpers.cpp(3): fatal error C1083: Cannot open include file: 'ISettingsModule.h': No such file or directory
```

# How to reproduce
Clone [SUDSExample](https://github.com/sinbad/SUDSExample), open with UE5.1, select `Platforms` -> `Windows` -> `Package Project`.

# Expected result
Standalone executable gets created.

# Actual result
```
UATHelper: Packaging (Windows): SUDSExample\Plugins\StevesUEHelpers\Source\StevesUEHelpers\Private\StevesUEHelpers.cpp(3): fatal error C1083: Cannot open include file: 'ISettingsModule.h': No such file or directory
```

# Notes
The [same issue got fixed by using the full path](https://github.com/ufna/VaRest/issues/159) to the header file. I've also seen a repository that uses `#if WITH_EDITOR` around the settings registration block. I'm not sure which fix is more correct, but the first one is easier to maintain, so I'm submitting a PR for that.

**Comment by sinbad** [comment]
Thanks but this has already been fixed, pulling the latest into your fork would have fixed it :) 

https://github.com/sinbad/StevesUEHelpers/commit/fe126f95a31a98f224f5f8a0be44958bc5e984f6

**Comment by lumpn** [comment]
> Thanks but this has already been fixed, pulling the latest into your fork would have fixed it :)

Kicking the ball right to you because SUDSExample doesn't use the latest. 😜 
Perhaps it would be better to track the head of the main branch for the submodules? https://stackoverflow.com/a/31851819

**Comment by sinbad** [comment]
Ah yeah, the examples project often gets behind. I'm already tracking the branch head, but you still have to pull changes & push them back to examples. I do that periodically but not for every single change since it often doesn't matter (like this one); no-one should be just copying the lib out of the examples demo, they should be grabbing it from the main source.
