### ISSUE TITLE
Compile failure due to default C++ standard below 20

### ISSUE THREAD

**Issue by Bigotry0** [sinbad/StevesUEHelpers#12]
#### It's possible that because my project was upgraded from an older version of Unreal to version 5.3.2, the default C++ standard in Unreal is not set to C++20. As a result, I encountered this error during compilation:
`
Error C7582 : ‘bEnableSmoothCollisionAvoidance’: default member initializers for bit-fields requires at least ‘/std:c++20’
`

#### I can resolve this issue by adding the following code in the `build.cs` module to set the C++ standard.
![image](https://github.com/user-attachments/assets/44b399a3-df3f-438d-985b-d5596e0c9fad)

#### I would greatly appreciate it if you could address this issue on the main branch! Thank you so much for providing these fantastic open-source tools!

**Comment by sinbad** [comment]
Rather than do this I've just removed the need for C++ 20 by initialising that member in the constructor instead. I didn't realised bitfield initialisation was only supported on 20. https://github.com/sinbad/StevesUEHelpers/commit/1e5fca94a22f6426eb75983bdadca69a347e47a0
