### ISSUE TITLE
A Small Spot - Bounds World vs Local

### ISSUE THREAD

**Issue by secondimpactrob** [sinbad/StevesUEHelpers#13]
Hi there,

Stumbled across your code while learning Unreal and trying to figure out the scene proxies for debug visualisation. Your blog post and source is very useful - thanks!!

While I was trying something out I noticed that focusing the camera on an object with StevesEditorVisComponent it was not centring right, and I believe it's because the bounds calculations aren't quite correct.

(The only reason I'm raising this is because your code was a valuable point of reference for me, and I hope it will be for others in future, so it's cleaner for future viewers if it's corrected.)

Specifically, in UStevesEditorVisComponent::CalcBounds:

**What it does at the moment:**
1. B = Super::CalcBounds(LocalToWorld)   _<- based on the source code I believe this comes back in World space, but the code treats it like it's in Local space_
2. for each shape:   B = B + NewShapeBounds (in Local-Space)  _<- Based on above this is actually adding a world space and local space bounds together_
3. before returning, it converts B into world space using B.TransformBy(LocalToWorld)

**What I think would be correct is either:**

A) Working in World Space the whole time:

1. B = Super::CalcBounds(LocalToWorld)
2. for every shape: B = B + NewShapeBounds.TransformBy(LocalToWorld)     _<- now adding two world space bounds together_
3. no need to convert on return since already in world space

or B) Working in Local Space the whole time:

1. B = Super::CalcBounds(LocalToWorld)          _<- comes back in world space_
2. Convert B into local space, e.g. TransformBy the inverse of LocalToWorld     _<- now working in local space_
3. for every shape: B = B + NewShapeBounds      _<- adding in local space_
4. before returning, convert B into world space using B.TransformBy(LocalToWorld)

**Comment by sinbad** [comment]
My apologies, I completely missed this thread and only just found it again. I usually rely on my email to remind me but it must have fallen through the cracks. I feel really bad considering the time you spent to write this!

You're completely right. I'm going to go for option B :)

**Comment by sinbad** [comment]
It was slightly simpler, just pass `FTransform::Identity` instead of `LocalToWorld` in the superclass call. Thanks again!
