### ISSUE TITLE
Visible visibility in MenuBase

### ISSUE THREAD

**Issue by FredrikAleksander** [sinbad/StevesUEHelpers#14]
Hi, I found what could be a bug, or possibly a area for improvement

https://github.com/sinbad/StevesUEHelpers/blob/master/Source/StevesUEHelpers/Private/StevesUI/MenuBase.cpp#L108

I think this line might work better if it uses ESlateVisibility::SelfHitTestInvisible instead ESlateVisibility::Visible, or maybe storing the default value on initialization in a variable, and set it to that value later, or just exposing it as a property. In my case I had a bugwhere I could no longer click a object in the world while a menu was visible, because my menu technically covered the entire screen (for alignment purposes), but only had a small widget that was actually visible, and it swallowed my mouse input. After I replaced with ESlateVisibility::SelfHitTestInvisible, it worked as expected

**Comment by sinbad** [comment]
This is actually deliberate precisely because it disables click-throughs; often you want the game below to be unresponsive to clicks while the menu is up, and for nested menus to block those below them if they're still visible. 

But it could probably be an option to allow click-throughs for cases like this.

**Comment by sinbad** [comment]
Yeah, I wrote this stuff for UE4 originally and for ages I planned to retire it and migrate to CommonUI, but having tried it extensively it has far too many problems with gamepad focus loss and just weird random behaviours so I ripped it out of my own project and went back to my old tried and tested approach 🙄 Glad you find it useful too!
