### ISSUE TITLE
Accepting PRs for additional UI Features?

### ISSUE THREAD

**Issue by emistorrs** [sinbad/StevesUEHelpers#15]
Hi Steve! I've been using your helpers, particularly for UI, and I'm finding features I would like to add. My question is, do any of these interest you, and would you be open to accepting PRs for them?

1. EnhancedInput bindings for MenuStack keys.
2. `bLoseFocusOnUnhover` for FocusableButton / FocusableCheckbox
3. FocusableBoundary, a widget that 
    - can be focused with (Enhanced)Input binding
    - when focused, navigation is trapped inside by default
    - can lose focus on a (Enhanced)Input binding. 
 (like the potion selection area in Slay The Spire. You press Square to focus it, navigate inside, and then Circle to leave)
![image](https://github.com/user-attachments/assets/e65aa981-4755-4d76-b33b-3fde8b9eb1d9)
5. `PlatformSupportsHardwareCursor` and other helper functionality from `CommonInput`
6. A `MenuSystem` that creates `MenuStacks` on demand in registered spots so opening Menus is simpler without having to create a new `MenuStack` every time. 
**or**
A `MenuSystem` that has the functionality of a `MenuStack` but uses multiple `MenuContainers` to help with naunced Z ordering with multiple menus.
7. Extend `FocusSystem` to allow FocusPriority switching when "Losing" focus on `FocusableWidgets` (Probably via a `Unfocus(Properly)` sort of function)

Ideally each feature would be submitted in a separate PR, and could be talked about individually. I'm just trying to decide how to resolve the UI needs for my game between this (very helpful!) library, CommonInput, and making my own Frankenstein's monster. 

Also open to just forking this repo and going at it, but I worry if I do so without intentionality, the likelihood of any changes getting upstreamed is low.

Let me know what you think!

**Comment by sinbad** [comment]
Hi, wow this all sounds great, I'm very happy to have contributions like this and it sounds like you have some very good ideas. Separate PRs would be perfect!

**Comment by sinbad** [comment]
I use Rider, which appears to come pre-configured to match the [Epic C++ standards](https://dev.epicgames.com/documentation/en-us/unreal-engine/epic-cplusplus-coding-standard-for-unreal-engine#codeformatting). So tabs for indenting, next-line curly braces rather than K&R. I didn't change very much from the standard Rider setup - I exported those settings but it only exports the diff from standard, which appeared to be just me enabling auto-wrapping. Everything else was standard.

**Comment by emistorrs** [comment]
I've created a [PR](https://github.com/sinbad/StevesUEHelpers/pull/16) to show some options for formatting. Let me know what you think!

**Comment by emistorrs** [comment]
Closing the issue! I'll be putting in some PRs over the next few weeks as I iron out our UI needs. Thank you!
