### ISSUE TITLE
When game is paused InputImage timer doesn't tick

### ISSUE THREAD

**Issue by dantreble** [sinbad/StevesUEHelpers#6]
https://github.com/sinbad/StevesUEHelpers/blob/997eddce01341a6e0cf3d9d11c4bcbf7ed11b97f/Source/StevesUEHelpers/Private/StevesUI/InputImage.cpp#L118

**Comment by sinbad** [comment]
Thanks for reporting, I hadn't noticed this problem in our game yet, definitely needed fixing. 👍
